# version: '3'

# services:
#   apache:
#     image: httpd:2.4
#     env_file:
#           - ".env"
#     volumes:
#       - ./app:/var/www/html
#       - .htaccess:/var/www/html/.htaccess
#       - ./server-config/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
#     depends_on:
#       - php
#   nginx:
#     image: nginx:1.13
#     env_file:
#           - ".env"
#     ports:
#       - 80:80
#     volumes:
#       - ./app:/var/www/html
#       - ./server-config/nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./server-config/nginx/nginx-camagru.conf:/etc/nginx/sites-enabled/
#     restart: always
#     depends_on:
#       - apache
#   php:
#     build: ./server-config/php/.
#     env_file:
#           - ".env"
#     volumes:
#       - ./app:/var/www/html
#       - ./server-config/php:/usr/local/etc/php
version: '3'

services:
  web:
      image: nginx:1.13
      container_name: web
      env_file:
          - ".env"
      volumes:
          - ./server-config/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./server-config/nginx/nginx-camagru.conf:/etc/nginx/sites-enabled/nginx-camagru.conf
          - ./app:${ROOT}
      ports:
          - "80:80"
      # restart: always
      depends_on:
          - php
          - mysqldb
  php:
      build: ./server-config/php/.
      env_file:
          - ".env"
      restart: always
      volumes:
          - "./server-config/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
          - "./app:${ROOT}"
  mailhog:
      image: mailhog/mailhog:v1.0.0
      container_name: mailhog
      restart: always
      ports:
        - "1025:1025"
        - "8025:8025"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      env_file:
          - ".env"
      ports:
          - "8080:80"
      environment:
        #   - PMA_ARBITRARY=1
          - PMA_HOST=${MYSQL_HOST}
      restart: always
      depends_on:
          - mysqldb
  mysqldb:
      image: mysql:${MYSQL_VERSION}
      container_name: ${MYSQL_HOST}
      restart: always
      env_file:
          - ".env"
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
          - "3306:3306"
      volumes:
          - "./app/data/db:/var/lib/mysql"